### ISSUE TITLE
How to get a comment body that triggered the job?

### ISSUE THREAD

**Issue by conf** [jenkinsci/github-pr-comment-build-plugin#22] opened 2020-07-01 08:00 UTC
Hello!

First of all, thank you for the wonderful plugin, it seems the best (and it seems the only) option for MultiBranch Pipelines that need to be triggered by a comment from the pull request.

However, I can't find a way to retrieve the exact phrase that the build has been triggered with.
I've tried to use `currentBuild.rawBuild.causes` and I get an array with a single object `[com.adobe.jenkins.github_pr_comment_build.GitHubPullRequestCommentCause@3f698a28]`, but I'm not sure how to proceed further, https://github.com/jenkinsci/github-pr-comment-build-plugin/blob/master/src/main/java/com/adobe/jenkins/github_pr_comment_build/GitHubPullRequestCommentCause.java doesn't seem to have any methods for retrieving the comment body, even `getCommentUrl()` method doesn't work. What am I doing wrong?

Ideally, it would be great to have this information already available as environment variable, similar to `CHANGE_ID`, `CHANGE_AUTHOR` and others.

**Comment by bluesliverx** [comment] 2020-07-08 05:00
Glad you like the plugin, it satisfied a need for us for sure. Hmm... not sure why comment URL wouldn't be able to be retrieved. Can you send the exact code you are using to access it?

I like the idea of adding another env var, but unfortunately that's a bit out of my wheel house, and may need some additional classes/extension points (I'm really not sure). It may be possible to override this when you schedule the job run, but I really don't know. PRs are absolutely welcome and encouraged, since I likely don't have any time to get to this soon just due to other work concerns.

**Comment by jebentier** [comment] 2020-10-14 14:21
@bluesliverx I've been using this plugin for quite some time and love the power that it adds to my GitHub repositories. 

I've been looking to build out a workaround to gain access to the comment body that triggered the build for a few days now.  With the code the way it is now, I've gone the route that you suggested through getting the comment URL from the build cause object. I think it will be a great improvement to this plugin (like you also mentioned) to allow access to the comment body itself through the cause object as well.  So I've opened up #25 to do just this, and I've opened [JENKINS-63938](https://issues.jenkins-ci.org/browse/JENKINS-63938) in the Jira to track this issue further as well.  

This is my first time contributing to Jenkins or a plugin, so please let me know if there is anything else I should do.

**Comment by bluesliverx** [comment] 2020-11-04 19:59
Thanks so much for the contribution @jebentier, sorry this has taken me so long to get to it. The build has failed, I'm still looking into why, likely Jenkins build made some updates (unrelated to your changes) that I haven't incorporated yet or something.

**Comment by bluesliverx** [comment] 2020-11-06 04:22
@jebentier, I finally got the build fixed, if you could take a look at my comments on the PR we can get this merged in.

**Comment by bluesliverx** [comment] 2020-11-06 22:13
I believe I just released version 2.2 that should have these fixes in them. It's been awhile since I released, so we'll see if that worked after a couple of hours...

**Comment by bluesliverx** [comment] 2020-11-09 15:29
Yup, that seems to have worked, let me know if the new version works out or now.

**Comment by jebinjeb** [comment] 2021-01-29 17:02
is this env available env.GITHUB_PR_COMMENT ? or any other way to get PR comments ?

**Comment by bluesliverx** [comment] 2021-01-29 18:47
Currently environment variables are not supported (PRs are welcome), but you can do it through retrieving the causes on the build and look for this one: https://github.com/jenkinsci/github-pr-comment-build-plugin/blob/master/src/main/java/com/adobe/jenkins/github_pr_comment_build/GitHubPullRequestCommentCause.java.

**Comment by bluesliverx** [comment] 2021-01-29 18:47
Closing this issue since I haven't heard back from @conf or @jebentier.

**Closed by bluesliverx** 2021-01-29 18:47 UTC
