### ISSUE TITLE
Retrieve comment author from the plugin

### ISSUE THREAD

**Issue by anandbvks** [jenkinsci/github-pr-comment-build-plugin#19] opened 2020-02-01 07:58 UTC
I'm using the github-pr-comment-build-plugin to start a build on Jenkins on a fixed commit pattern. The catch here is that, I need only few users to trigger the build via their comment. 

I can't restrict authors on Github as I want all authors to make comments on the PR but only a few authors' comments to trigger the build

The approach I'm trying to use here is by retrieving the author of the comment during the build (that was triggered by the comment), I'll abort/kill the build if the author is not part of the approved list of authors.

Is there a way I can pull the author information using this plugin?
I use Scripted Pipeline.

Thanks for your time!

**Comment by bluesliverx** [comment] 2020-02-03 16:38
The plugin adds a cause to any build it triggers with information about the comment, including the author. See https://github.com/jenkinsci/github-pr-comment-build-plugin/blob/master/src/main/java/com/adobe/jenkins/github_pr_comment_build/GitHubPullRequestCommentCause.java or the other two causes next to it.

This can be retrieved from the pipeline using the `currentBuild.rawBuild.causes` (see https://javadoc.jenkins-ci.org/hudson/model/Run.html#getCauses--). It would need to be in a method marked `@NonCPS` because rawBuild is not serializable, and it may need to be approved in the script console, not sure.

**Comment by bluesliverx** [comment] 2020-07-08 05:02
Actually, looking at it, I don't see any fields for the author, but that would be easy to add. Just add the field in the cause class and then add it to the constructor in the events subscriber(s). That would do it, then you could just access it through the causes.

**Comment by bluesliverx** [comment] 2021-09-20 17:47
I pushed a fix for this, as soon as it builds and merges, I'll trigger a new release.

**Closed** 2021-09-20 17:56 UTC

**Comment by bluesliverx** [comment] 2021-09-20 18:01
Waiting for https://github.com/jenkins-infra/repository-permissions-updater/pull/2090 to be merged before this can be released.

**Comment by bluesliverx** [comment] 2021-09-21 00:57
I changed the versioning scheme for incremental releases, and 58.v945be9f1661f has been released with the fix for this.
